// app/head.tsx
export default function Head() {
  return (
    <>
      <title>Tife Portfolio</title>
      <meta
        name="description"
        content="Generated by Boluwatife Eniola Osineye"
      />
      <link rel="icon" href="/favicon.png" type="image/png" />
    </>
  );
}
